# Server settings
server:
    port: 6006
      

# DATASOURCE
jdbc:
    #dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    dataSourceClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.154.157.46/game_center?useUnicode=true&amp;characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: tvgc
    password: tvcldqsr203awd
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    minimumIdle: 1
    maximumPoolSize: 2

# SPRING PROFILES
spring:       
    # HTTP ENCODING
    #mvc.favicon.enabled: false
    #resources.add-mappings: true
    application:
        name: benaiMahjong
    boot:
        admin:
            url: http://localhost:${server.port}
    jackson:
        serialization:
            indent_output: true
            
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
        
    messages:
        basename: locale/messages
        cache-seconds: 3600
        encoding : UTF-8
    # REDIS (RedisProperties)
    redis:
        database: 3
        databaseauth: 0
        host: 117.121.2.139
        password: Hz%qsdmzjlqh6
        port: 6379
        pool.max-idle: 8 
        pool.min-idle: 5
        pool.max-active: 50
        pool.max-wait: 1000

endpoints:
    health:
        enabled: true
        sensitive: false
# MyBatis
mybatis:
    typeAliasesPackage: com.letv.tvgc.sylvanas.dao.model
    configLocation: classpath:/conf/mybatis-config.xml