// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandBase.proto

package com.benai.mahjong.message;

public final class CommandBase {
  private CommandBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.CommonMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命令ID
     * </pre>
     *
     * <code>int32 cmdId = 1;</code>
     */
    int getCmdId();

    /**
     * <pre>
     * 消息体数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code base.CommonMessage}
   */
  public  static final class CommonMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:base.CommonMessage)
      CommonMessageOrBuilder {
    // Use CommonMessage.newBuilder() to construct.
    private CommonMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonMessage() {
      cmdId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CommonMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cmdId_ = input.readInt32();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benai.mahjong.message.CommandBase.internal_static_base_CommonMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benai.mahjong.message.CommandBase.internal_static_base_CommonMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benai.mahjong.message.CommandBase.CommonMessage.class, com.benai.mahjong.message.CommandBase.CommonMessage.Builder.class);
    }

    public static final int CMDID_FIELD_NUMBER = 1;
    private int cmdId_;
    /**
     * <pre>
     * 命令ID
     * </pre>
     *
     * <code>int32 cmdId = 1;</code>
     */
    public int getCmdId() {
      return cmdId_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 消息体数据
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdId_ != 0) {
        output.writeInt32(1, cmdId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.benai.mahjong.message.CommandBase.CommonMessage)) {
        return super.equals(obj);
      }
      com.benai.mahjong.message.CommandBase.CommonMessage other = (com.benai.mahjong.message.CommandBase.CommonMessage) obj;

      boolean result = true;
      result = result && (getCmdId()
          == other.getCmdId());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMDID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.CommonMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.benai.mahjong.message.CommandBase.CommonMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code base.CommonMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:base.CommonMessage)
        com.benai.mahjong.message.CommandBase.CommonMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_CommonMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_CommonMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benai.mahjong.message.CommandBase.CommonMessage.class, com.benai.mahjong.message.CommandBase.CommonMessage.Builder.class);
      }

      // Construct using com.benai.mahjong.message.CommandBase.CommonMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_CommonMessage_descriptor;
      }

      public com.benai.mahjong.message.CommandBase.CommonMessage getDefaultInstanceForType() {
        return com.benai.mahjong.message.CommandBase.CommonMessage.getDefaultInstance();
      }

      public com.benai.mahjong.message.CommandBase.CommonMessage build() {
        com.benai.mahjong.message.CommandBase.CommonMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benai.mahjong.message.CommandBase.CommonMessage buildPartial() {
        com.benai.mahjong.message.CommandBase.CommonMessage result = new com.benai.mahjong.message.CommandBase.CommonMessage(this);
        result.cmdId_ = cmdId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benai.mahjong.message.CommandBase.CommonMessage) {
          return mergeFrom((com.benai.mahjong.message.CommandBase.CommonMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benai.mahjong.message.CommandBase.CommonMessage other) {
        if (other == com.benai.mahjong.message.CommandBase.CommonMessage.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benai.mahjong.message.CommandBase.CommonMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benai.mahjong.message.CommandBase.CommonMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmdId_ ;
      /**
       * <pre>
       * 命令ID
       * </pre>
       *
       * <code>int32 cmdId = 1;</code>
       */
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <pre>
       * 命令ID
       * </pre>
       *
       * <code>int32 cmdId = 1;</code>
       */
      public Builder setCmdId(int value) {
        
        cmdId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令ID
       * </pre>
       *
       * <code>int32 cmdId = 1;</code>
       */
      public Builder clearCmdId() {
        
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 消息体数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 消息体数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体数据
       * </pre>
       *
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:base.CommonMessage)
    }

    // @@protoc_insertion_point(class_scope:base.CommonMessage)
    private static final com.benai.mahjong.message.CommandBase.CommonMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.benai.mahjong.message.CommandBase.CommonMessage();
    }

    public static com.benai.mahjong.message.CommandBase.CommonMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonMessage>
        PARSER = new com.google.protobuf.AbstractParser<CommonMessage>() {
      public CommonMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommonMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonMessage> getParserForType() {
      return PARSER;
    }

    public com.benai.mahjong.message.CommandBase.CommonMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_base_CommonMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_base_CommonMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CommandBase.proto\022\004base\",\n\rCommonMessa" +
      "ge\022\r\n\005cmdId\030\001 \001(\005\022\014\n\004data\030\002 \001(\014B(\n\031com.b" +
      "enai.mahjong.messageB\013CommandBaseb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_base_CommonMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_base_CommonMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_base_CommonMessage_descriptor,
        new java.lang.String[] { "CmdId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
