// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandBase.proto

package com.benai.mahjong.message;

public final class CommandBase {
  private CommandBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageNameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.MessageName)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 message_field = 1;</code>
     */
    int getMessageField();
  }
  /**
   * Protobuf type {@code base.MessageName}
   */
  public  static final class MessageName extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:base.MessageName)
      MessageNameOrBuilder {
    // Use MessageName.newBuilder() to construct.
    private MessageName(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageName() {
      messageField_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageField_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.benai.mahjong.message.CommandBase.internal_static_base_MessageName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.benai.mahjong.message.CommandBase.internal_static_base_MessageName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.benai.mahjong.message.CommandBase.MessageName.class, com.benai.mahjong.message.CommandBase.MessageName.Builder.class);
    }

    public static final int MESSAGE_FIELD_FIELD_NUMBER = 1;
    private int messageField_;
    /**
     * <code>uint32 message_field = 1;</code>
     */
    public int getMessageField() {
      return messageField_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageField_ != 0) {
        output.writeUInt32(1, messageField_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageField_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, messageField_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.benai.mahjong.message.CommandBase.MessageName)) {
        return super.equals(obj);
      }
      com.benai.mahjong.message.CommandBase.MessageName other = (com.benai.mahjong.message.CommandBase.MessageName) obj;

      boolean result = true;
      result = result && (getMessageField()
          == other.getMessageField());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getMessageField();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.benai.mahjong.message.CommandBase.MessageName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.benai.mahjong.message.CommandBase.MessageName prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code base.MessageName}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:base.MessageName)
        com.benai.mahjong.message.CommandBase.MessageNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_MessageName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_MessageName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.benai.mahjong.message.CommandBase.MessageName.class, com.benai.mahjong.message.CommandBase.MessageName.Builder.class);
      }

      // Construct using com.benai.mahjong.message.CommandBase.MessageName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageField_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.benai.mahjong.message.CommandBase.internal_static_base_MessageName_descriptor;
      }

      public com.benai.mahjong.message.CommandBase.MessageName getDefaultInstanceForType() {
        return com.benai.mahjong.message.CommandBase.MessageName.getDefaultInstance();
      }

      public com.benai.mahjong.message.CommandBase.MessageName build() {
        com.benai.mahjong.message.CommandBase.MessageName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.benai.mahjong.message.CommandBase.MessageName buildPartial() {
        com.benai.mahjong.message.CommandBase.MessageName result = new com.benai.mahjong.message.CommandBase.MessageName(this);
        result.messageField_ = messageField_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.benai.mahjong.message.CommandBase.MessageName) {
          return mergeFrom((com.benai.mahjong.message.CommandBase.MessageName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.benai.mahjong.message.CommandBase.MessageName other) {
        if (other == com.benai.mahjong.message.CommandBase.MessageName.getDefaultInstance()) return this;
        if (other.getMessageField() != 0) {
          setMessageField(other.getMessageField());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.benai.mahjong.message.CommandBase.MessageName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.benai.mahjong.message.CommandBase.MessageName) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageField_ ;
      /**
       * <code>uint32 message_field = 1;</code>
       */
      public int getMessageField() {
        return messageField_;
      }
      /**
       * <code>uint32 message_field = 1;</code>
       */
      public Builder setMessageField(int value) {
        
        messageField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 message_field = 1;</code>
       */
      public Builder clearMessageField() {
        
        messageField_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:base.MessageName)
    }

    // @@protoc_insertion_point(class_scope:base.MessageName)
    private static final com.benai.mahjong.message.CommandBase.MessageName DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.benai.mahjong.message.CommandBase.MessageName();
    }

    public static com.benai.mahjong.message.CommandBase.MessageName getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageName>
        PARSER = new com.google.protobuf.AbstractParser<MessageName>() {
      public MessageName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageName(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageName> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageName> getParserForType() {
      return PARSER;
    }

    public com.benai.mahjong.message.CommandBase.MessageName getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_base_MessageName_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_base_MessageName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CommandBase.proto\022\004base\"$\n\013MessageName" +
      "\022\025\n\rmessage_field\030\001 \001(\rB(\n\031com.benai.mah" +
      "jong.messageB\013CommandBaseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_base_MessageName_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_base_MessageName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_base_MessageName_descriptor,
        new java.lang.String[] { "MessageField", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
